### ISSUE TITLE
Non-formal requirements should not break typechecking

### ISSUE THREAD

**Issue by manthonyaiello** [lgwagner/SpeAR#85]
In the following:

```
Specification non_formal

Inputs:

Outputs:

State:
  s is a bool

Requirements:
  r1: s == 1

  n: "this is not formal"

  r2: s == 1
```

r1 correctly typechecks (raises a type error) however r2 does not (no type error is raised).
